Support run once via interval argument
flink-ci/ci-bot pull request #1
Opened 2021-05-10 01:10 UTC by xushiyan

To allow run-once mode by setting polling interval to non-positive number.

2021-05-10 01:13 UTC, xushiyan commented
Hi @zentol I'd like to add this feature. However, I'm not sure why 9b844dc64c74694d0c1ebab8834a4eb0b5e1bbd4 was introduced. It seems to create a double while-true-loop given `com.ververica.CiBot#run` already running in a loop and catches exceptions within itself.

2021-05-17 09:04 UTC, zentol requested changes
`com.ververica.CiBot#run` does not catch exceptions in the loop, because it is simpler to just restart the whole thing if an error occurred than trying to account for possible inconsistencies in the internal state. Until 9b844dc64c74694d0c1ebab8834a4eb0b5e1bbd4 this was a manual step, which became a bit annoying over time.

As for the propose change, I had a comment on the code structuring.

2021-05-17 09:04 UTC, zentol commented on src/main/java/com/ververica/CiBot.java
> +			do {
let's move the inner `try` block into a separate method, and structure `run` like this:

```
if (runContinuously) {
	while (true) {
		internalRun()
		<sleep>
	}
} else {
	internalRun()
}
```

2021-05-27 07:50 UTC, merged

2021-06-20 21:47 UTC, xushiyan commented
@zentol sorry this slipped through me...thanks a lot for getting this landed!